export type FnRef = {
  name: string;
  category: string;
  syntax: string;
  desc: string;
  example: string;
  result: string;
  note?: string;
  lesson?: string;
};

/** Complete A-Z Excel function reference, grouped the way Excel groups them. */
export const FUNCTIONS: FnRef[] = [
  // ---------- Math & Trig ----------
  { name: "SUM", category: "Math", syntax: "=SUM(number1;[number2];...)", desc: "Adds all the numbers in the arguments.", example: "=SUM(A1:A10)", result: "Total of A1:A10", note: "Press Alt + = to insert it automatically.", lesson: "sum" },
  { name: "SUMIF", category: "Math", syntax: "=SUMIF(range;criteria;[sum_range])", desc: "Adds the cells whose matching row meets one condition.", example: '=SUMIF(C:C;"North";B:B)', result: "Total of North rows", lesson: "sumif" },
  { name: "SUMIFS", category: "Math", syntax: "=SUMIFS(sum_range;crit_range1;crit1;...)", desc: "Adds cells that meet several conditions.", example: '=SUMIFS(B:B;C:C;"North";D:D;2024)', result: "Filtered total", note: "The sum range comes first, unlike SUMIF.", lesson: "sumifs" },
  { name: "SUMPRODUCT", category: "Math", syntax: "=SUMPRODUCT(array1;[array2];...)", desc: "Multiplies arrays element by element and adds the results.", example: "=SUMPRODUCT(B2:B9;C2:C9)", result: "Qty x price total", lesson: "sumproduct" },
  { name: "SUBTOTAL", category: "Math", syntax: "=SUBTOTAL(function_num;ref1;...)", desc: "Aggregates a range, optionally ignoring hidden rows.", example: "=SUBTOTAL(109;B2:B50)", result: "Sum of visible rows", note: "1-11 include hidden rows, 101-111 ignore them.", lesson: "filter-tool" },
  { name: "AGGREGATE", category: "Math", syntax: "=AGGREGATE(fn;options;ref)", desc: "Like SUBTOTAL but can also ignore errors and nested subtotals.", example: "=AGGREGATE(9;6;B2:B50)", result: "Sum ignoring errors" },
  { name: "PRODUCT", category: "Math", syntax: "=PRODUCT(number1;...)", desc: "Multiplies all the numbers given.", example: "=PRODUCT(B2:D2)", result: "B2*C2*D2", lesson: "multiply" },
  { name: "QUOTIENT", category: "Math", syntax: "=QUOTIENT(numerator;denominator)", desc: "Returns the whole-number part of a division.", example: "=QUOTIENT(17;5)", result: "3", lesson: "division" },
  { name: "MOD", category: "Math", syntax: "=MOD(number;divisor)", desc: "Returns the remainder after division.", example: "=MOD(17;5)", result: "2", note: "MOD(row;2)=0 finds even rows for banded formatting." },
  { name: "ROUND", category: "Math", syntax: "=ROUND(number;num_digits)", desc: "Rounds to a set number of digits.", example: "=ROUND(2.567;1)", result: "2.6" },
  { name: "ROUNDUP", category: "Math", syntax: "=ROUNDUP(number;num_digits)", desc: "Always rounds away from zero.", example: "=ROUNDUP(2.11;1)", result: "2.2" },
  { name: "ROUNDDOWN", category: "Math", syntax: "=ROUNDDOWN(number;num_digits)", desc: "Always rounds towards zero.", example: "=ROUNDDOWN(2.99;1)", result: "2.9" },
  { name: "MROUND", category: "Math", syntax: "=MROUND(number;multiple)", desc: "Rounds to the nearest multiple.", example: "=MROUND(23;5)", result: "25" },
  { name: "CEILING.MATH", category: "Math", syntax: "=CEILING.MATH(number;[significance])", desc: "Rounds up to the nearest multiple.", example: "=CEILING.MATH(4.2)", result: "5" },
  { name: "FLOOR.MATH", category: "Math", syntax: "=FLOOR.MATH(number;[significance])", desc: "Rounds down to the nearest multiple.", example: "=FLOOR.MATH(4.9)", result: "4" },
  { name: "INT", category: "Math", syntax: "=INT(number)", desc: "Rounds down to the nearest integer.", example: "=INT(-2.3)", result: "-3" },
  { name: "TRUNC", category: "Math", syntax: "=TRUNC(number;[digits])", desc: "Chops off decimals without rounding.", example: "=TRUNC(-2.9)", result: "-2" },
  { name: "ABS", category: "Math", syntax: "=ABS(number)", desc: "Returns the value without its sign.", example: "=ABS(-15)", result: "15" },
  { name: "SIGN", category: "Math", syntax: "=SIGN(number)", desc: "Returns 1, 0 or -1 depending on the sign.", example: "=SIGN(-4)", result: "-1" },
  { name: "POWER", category: "Math", syntax: "=POWER(number;power)", desc: "Raises a number to a power.", example: "=POWER(2;10)", result: "1024" },
  { name: "SQRT", category: "Math", syntax: "=SQRT(number)", desc: "Square root of a positive number.", example: "=SQRT(144)", result: "12" },
  { name: "EXP", category: "Math", syntax: "=EXP(number)", desc: "e raised to the given power.", example: "=EXP(1)", result: "2.71828" },
  { name: "LN", category: "Math", syntax: "=LN(number)", desc: "Natural logarithm.", example: "=LN(100)", result: "4.605" },
  { name: "LOG", category: "Math", syntax: "=LOG(number;[base])", desc: "Logarithm to a chosen base.", example: "=LOG(8;2)", result: "3" },
  { name: "LOG10", category: "Math", syntax: "=LOG10(number)", desc: "Base-10 logarithm.", example: "=LOG10(1000)", result: "3" },
  { name: "RAND", category: "Math", syntax: "=RAND()", desc: "Random decimal between 0 and 1.", example: "=RAND()", result: "0.4312..." },
  { name: "RANDBETWEEN", category: "Math", syntax: "=RANDBETWEEN(bottom;top)", desc: "Random whole number in a range.", example: "=RANDBETWEEN(1;100)", result: "57" },
  { name: "RANDARRAY", category: "Math", syntax: "=RANDARRAY([rows];[cols];[min];[max];[whole])", desc: "Spills a block of random values.", example: "=RANDARRAY(5;1;1;10;TRUE)", result: "5 random integers", lesson: "randarray" },
  { name: "GCD", category: "Math", syntax: "=GCD(number1;...)", desc: "Greatest common divisor.", example: "=GCD(24;36)", result: "12" },
  { name: "LCM", category: "Math", syntax: "=LCM(number1;...)", desc: "Lowest common multiple.", example: "=LCM(4;6)", result: "12" },
  { name: "FACT", category: "Math", syntax: "=FACT(number)", desc: "Factorial of a number.", example: "=FACT(5)", result: "120" },
  { name: "PI", category: "Math", syntax: "=PI()", desc: "The value of pi.", example: "=PI()", result: "3.14159" },
  { name: "SIN", category: "Math", syntax: "=SIN(number)", desc: "Sine of an angle in radians.", example: "=SIN(PI()/2)", result: "1" },
  { name: "COS", category: "Math", syntax: "=COS(number)", desc: "Cosine of an angle in radians.", example: "=COS(0)", result: "1" },
  { name: "TAN", category: "Math", syntax: "=TAN(number)", desc: "Tangent of an angle in radians.", example: "=TAN(0)", result: "0" },
  { name: "RADIANS", category: "Math", syntax: "=RADIANS(degrees)", desc: "Converts degrees to radians.", example: "=RADIANS(180)", result: "3.14159" },
  { name: "DEGREES", category: "Math", syntax: "=DEGREES(angle)", desc: "Converts radians to degrees.", example: "=DEGREES(PI())", result: "180" },
  { name: "EVEN", category: "Math", syntax: "=EVEN(number)", desc: "Rounds up to the nearest even integer.", example: "=EVEN(3)", result: "4" },
  { name: "ODD", category: "Math", syntax: "=ODD(number)", desc: "Rounds up to the nearest odd integer.", example: "=ODD(2)", result: "3" },
  { name: "SUMSQ", category: "Math", syntax: "=SUMSQ(number1;...)", desc: "Sum of the squares.", example: "=SUMSQ(3;4)", result: "25" },
  { name: "SEQUENCE", category: "Math", syntax: "=SEQUENCE(rows;[cols];[start];[step])", desc: "Generates a spilled series of numbers.", example: "=SEQUENCE(5)", result: "1,2,3,4,5", lesson: "sequence" },

  // ---------- Statistical ----------
  { name: "AVERAGE", category: "Statistical", syntax: "=AVERAGE(number1;...)", desc: "Arithmetic mean, ignoring blanks and text.", example: "=AVERAGE(B2:B10)", result: "Mean value", lesson: "average" },
  { name: "AVERAGEIF", category: "Statistical", syntax: "=AVERAGEIF(range;criteria;[avg_range])", desc: "Mean of the rows that meet one condition.", example: '=AVERAGEIF(B:B;"<>0")', result: "Mean excluding zeros", lesson: "averageif" },
  { name: "AVERAGEIFS", category: "Statistical", syntax: "=AVERAGEIFS(avg_range;crit_range1;crit1;...)", desc: "Mean with several conditions.", example: '=AVERAGEIFS(B:B;C:C;"North";D:D;">0")', result: "Filtered mean" },
  { name: "AVERAGEA", category: "Statistical", syntax: "=AVERAGEA(value1;...)", desc: "Mean that counts text as 0 and TRUE as 1.", example: "=AVERAGEA(A1:A5)", result: "Mean incl. text" },
  { name: "COUNT", category: "Statistical", syntax: "=COUNT(value1;...)", desc: "Counts cells containing numbers.", example: "=COUNT(B2:B50)", result: "Number of numeric cells", lesson: "count" },
  { name: "COUNTA", category: "Statistical", syntax: "=COUNTA(value1;...)", desc: "Counts cells that are not empty.", example: "=COUNTA(A2:A50)", result: "Number of records", lesson: "counta" },
  { name: "COUNTBLANK", category: "Statistical", syntax: "=COUNTBLANK(range)", desc: "Counts empty cells.", example: "=COUNTBLANK(A2:A50)", result: "Gaps in the data", lesson: "isblank" },
  { name: "COUNTIF", category: "Statistical", syntax: "=COUNTIF(range;criteria)", desc: "Counts cells meeting one condition.", example: '=COUNTIF(A:A;"North")', result: "Matches", lesson: "countif" },
  { name: "COUNTIFS", category: "Statistical", syntax: "=COUNTIFS(range1;crit1;...)", desc: "Counts rows meeting several conditions.", example: '=COUNTIFS(C:C;"North";E:E;"Open")', result: "Filtered count", lesson: "countifs" },
  { name: "MAX", category: "Statistical", syntax: "=MAX(number1;...)", desc: "Largest value in the range.", example: "=MAX(B2:B50)", result: "Highest number", lesson: "max" },
  { name: "MAXIFS", category: "Statistical", syntax: "=MAXIFS(max_range;crit_range1;crit1;...)", desc: "Largest value that meets conditions.", example: '=MAXIFS(B:B;C:C;"North")', result: "Biggest North sale", lesson: "maxifs" },
  { name: "MIN", category: "Statistical", syntax: "=MIN(number1;...)", desc: "Smallest value in the range.", example: "=MIN(B2:B50)", result: "Lowest number", lesson: "min" },
  { name: "MINIFS", category: "Statistical", syntax: "=MINIFS(min_range;crit_range1;crit1;...)", desc: "Smallest value that meets conditions.", example: '=MINIFS(C:C;A:A;"Widget")', result: "Cheapest widget", lesson: "minifs" },
  { name: "LARGE", category: "Statistical", syntax: "=LARGE(array;k)", desc: "The k-th largest value.", example: "=LARGE(B2:B50;3)", result: "3rd biggest" },
  { name: "SMALL", category: "Statistical", syntax: "=SMALL(array;k)", desc: "The k-th smallest value.", example: "=SMALL(B2:B50;2)", result: "2nd smallest" },
  { name: "MEDIAN", category: "Statistical", syntax: "=MEDIAN(number1;...)", desc: "Middle value of the set.", example: "=MEDIAN(B2:B50)", result: "Midpoint" },
  { name: "MODE.SNGL", category: "Statistical", syntax: "=MODE.SNGL(number1;...)", desc: "Most frequently occurring value.", example: "=MODE.SNGL(B2:B50)", result: "Most common" },
  { name: "STDEV.S", category: "Statistical", syntax: "=STDEV.S(number1;...)", desc: "Standard deviation of a sample.", example: "=STDEV.S(B2:B50)", result: "Spread" },
  { name: "STDEV.P", category: "Statistical", syntax: "=STDEV.P(number1;...)", desc: "Standard deviation of a whole population.", example: "=STDEV.P(B2:B50)", result: "Spread" },
  { name: "VAR.S", category: "Statistical", syntax: "=VAR.S(number1;...)", desc: "Variance of a sample.", example: "=VAR.S(B2:B50)", result: "Variance" },
  { name: "RANK.EQ", category: "Statistical", syntax: "=RANK.EQ(number;ref;[order])", desc: "Position of a value in a list.", example: "=RANK.EQ(B2;$B$2:$B$50;0)", result: "League position" },
  { name: "PERCENTILE.INC", category: "Statistical", syntax: "=PERCENTILE.INC(array;k)", desc: "Value at a given percentile.", example: "=PERCENTILE.INC(B2:B50;0.9)", result: "90th percentile" },
  { name: "QUARTILE.INC", category: "Statistical", syntax: "=QUARTILE.INC(array;quart)", desc: "Value at a quartile boundary.", example: "=QUARTILE.INC(B2:B50;1)", result: "Lower quartile" },
  { name: "PERCENTRANK.INC", category: "Statistical", syntax: "=PERCENTRANK.INC(array;x)", desc: "Percentile rank of a value.", example: "=PERCENTRANK.INC(B2:B50;B2)", result: "0.82" },
  { name: "CORREL", category: "Statistical", syntax: "=CORREL(array1;array2)", desc: "Correlation coefficient of two sets.", example: "=CORREL(B2:B50;C2:C50)", result: "-1 to 1" },
  { name: "FORECAST.LINEAR", category: "Statistical", syntax: "=FORECAST.LINEAR(x;known_ys;known_xs)", desc: "Predicts a value on a straight-line trend.", example: "=FORECAST.LINEAR(13;B2:B13;A2:A13)", result: "Next month" },
  { name: "TREND", category: "Statistical", syntax: "=TREND(known_ys;[known_xs];[new_xs])", desc: "Fits a linear trend and returns values along it.", example: "=TREND(B2:B13)", result: "Trend series" },
  { name: "SLOPE", category: "Statistical", syntax: "=SLOPE(known_ys;known_xs)", desc: "Slope of the regression line.", example: "=SLOPE(B2:B13;A2:A13)", result: "Gradient" },
  { name: "INTERCEPT", category: "Statistical", syntax: "=INTERCEPT(known_ys;known_xs)", desc: "Where the regression line meets the y axis.", example: "=INTERCEPT(B2:B13;A2:A13)", result: "Intercept" },

  // ---------- Logical ----------
  { name: "IF", category: "Logical", syntax: "=IF(test;value_if_true;value_if_false)", desc: "Returns one value when the test is true and another when it is false.", example: '=IF(B2>=50;"Pass";"Fail")', result: "Pass or Fail", lesson: "if" },
  { name: "IFS", category: "Logical", syntax: "=IFS(test1;val1;test2;val2;...)", desc: "Checks several conditions in order, no nesting needed.", example: '=IFS(B2>=90;"A";B2>=75;"B";TRUE;"C")', result: "Grade", lesson: "nested-if" },
  { name: "AND", category: "Logical", syntax: "=AND(logical1;...)", desc: "TRUE only when every condition is true.", example: "=AND(B2>0;C2>0)", result: "TRUE / FALSE", lesson: "and-or" },
  { name: "OR", category: "Logical", syntax: "=OR(logical1;...)", desc: "TRUE when at least one condition is true.", example: '=OR(C2="North";C2="South")', result: "TRUE / FALSE", lesson: "and-or" },
  { name: "NOT", category: "Logical", syntax: "=NOT(logical)", desc: "Reverses TRUE and FALSE.", example: "=NOT(A1>10)", result: "TRUE / FALSE", lesson: "and-or" },
  { name: "XOR", category: "Logical", syntax: "=XOR(logical1;...)", desc: "TRUE when an odd number of conditions are true.", example: "=XOR(A1>1;B1>1)", result: "TRUE / FALSE" },
  { name: "IFERROR", category: "Logical", syntax: "=IFERROR(value;value_if_error)", desc: "Replaces any error with your own value.", example: '=IFERROR(B2/C2;"-")', result: "Clean result", lesson: "iferror" },
  { name: "IFNA", category: "Logical", syntax: "=IFNA(value;value_if_na)", desc: "Replaces only the #N/A error.", example: '=IFNA(VLOOKUP(...);"Not found")', result: "Clean lookup", lesson: "iferror" },
  { name: "SWITCH", category: "Logical", syntax: "=SWITCH(expr;val1;res1;...;[default])", desc: "Compares one value against a list of results.", example: '=SWITCH(A2;1;"Low";2;"Mid";"High")', result: "Label" },
  { name: "TRUE", category: "Logical", syntax: "=TRUE()", desc: "Returns the logical value TRUE.", example: "=TRUE()", result: "TRUE" },
  { name: "FALSE", category: "Logical", syntax: "=FALSE()", desc: "Returns the logical value FALSE.", example: "=FALSE()", result: "FALSE" },
  { name: "LET", category: "Logical", syntax: "=LET(name1;value1;...;calculation)", desc: "Names intermediate results inside a formula.", example: "=LET(x;A2*B2;x+x*0.2)", result: "Readable formula", lesson: "let" },
  { name: "LAMBDA", category: "Logical", syntax: "=LAMBDA(param1;...;calculation)", desc: "Creates your own reusable function.", example: "=LAMBDA(r;c;(r-c)/r)(B2;C2)", result: "Custom result", lesson: "lambda" },

  // ---------- Lookup & Reference ----------
  { name: "VLOOKUP", category: "Lookup", syntax: "=VLOOKUP(value;table;col_index;[range_lookup])", desc: "Searches down the first column and returns a value from a counted column.", example: "=VLOOKUP(A2;$H$2:$K$50;3;FALSE)", result: "Matching value", note: "Always pass FALSE for an exact match.", lesson: "vlookup" },
  { name: "HLOOKUP", category: "Lookup", syntax: "=HLOOKUP(value;table;row_index;[range_lookup])", desc: "Searches across the top row and returns a value from a counted row.", example: '=HLOOKUP("Mar";$B$1:$M$20;5;FALSE)', result: "March value", lesson: "hlookup" },
  { name: "XLOOKUP", category: "Lookup", syntax: "=XLOOKUP(value;lookup_array;return_array;[if_not_found];[match_mode];[search_mode])", desc: "Modern lookup in any direction with built-in not-found handling.", example: '=XLOOKUP(A2;Ids;Names;"Not found")', result: "Matching value", lesson: "xlookup" },
  { name: "INDEX", category: "Lookup", syntax: "=INDEX(array;row_num;[col_num])", desc: "Returns the value at a position in a range.", example: "=INDEX(A2:D50;5;3)", result: "Cell value", lesson: "index" },
  { name: "MATCH", category: "Lookup", syntax: "=MATCH(value;array;[match_type])", desc: "Returns the position of a value in a list.", example: '=MATCH("Widget";A2:A50;0)', result: "Row number", lesson: "match" },
  { name: "XMATCH", category: "Lookup", syntax: "=XMATCH(value;array;[match_mode];[search_mode])", desc: "Modern MATCH with reverse search and wildcard modes.", example: "=XMATCH(A2;B2:B50;0;-1)", result: "Last match position" },
  { name: "CHOOSE", category: "Lookup", syntax: "=CHOOSE(index;value1;...)", desc: "Picks a value from a list by position.", example: '=CHOOSE(2;"Low";"Mid";"High")', result: "Mid" },
  { name: "OFFSET", category: "Lookup", syntax: "=OFFSET(ref;rows;cols;[height];[width])", desc: "Returns a range shifted from a starting point.", example: "=SUM(OFFSET(A1;0;0;10;1))", result: "Dynamic range", note: "Volatile - recalculates constantly. Prefer INDEX." },
  { name: "INDIRECT", category: "Lookup", syntax: "=INDIRECT(ref_text)", desc: "Turns text into a real cell reference.", example: '=INDIRECT("Sheet2!A1")', result: "Value from Sheet2" },
  { name: "ROW", category: "Lookup", syntax: "=ROW([reference])", desc: "Returns the row number.", example: "=ROW(A5)", result: "5" },
  { name: "ROWS", category: "Lookup", syntax: "=ROWS(array)", desc: "Counts the rows in a reference.", example: "=ROWS(A2:A50)", result: "49" },
  { name: "COLUMN", category: "Lookup", syntax: "=COLUMN([reference])", desc: "Returns the column number.", example: "=COLUMN(C1)", result: "3" },
  { name: "COLUMNS", category: "Lookup", syntax: "=COLUMNS(array)", desc: "Counts the columns in a reference.", example: "=COLUMNS(A1:D1)", result: "4" },
  { name: "TRANSPOSE", category: "Lookup", syntax: "=TRANSPOSE(array)", desc: "Flips rows into columns.", example: "=TRANSPOSE(A1:A5)", result: "Horizontal list" },
  { name: "HYPERLINK", category: "Lookup", syntax: "=HYPERLINK(link_location;[friendly_name])", desc: "Creates a clickable link.", example: '=HYPERLINK("https://x.com";"Open")', result: "Link" },
  { name: "FORMULATEXT", category: "Lookup", syntax: "=FORMULATEXT(reference)", desc: "Shows another cell's formula as text.", example: "=FORMULATEXT(B2)", result: "=SUM(A1:A5)", lesson: "formulatext" },
  { name: "AREAS", category: "Lookup", syntax: "=AREAS(reference)", desc: "Counts the areas in a reference.", example: "=AREAS((A1:B2;D1:E2))", result: "2" },

  // ---------- Dynamic arrays ----------
  { name: "UNIQUE", category: "Dynamic array", syntax: "=UNIQUE(array;[by_col];[exactly_once])", desc: "Returns the distinct values from a range.", example: "=UNIQUE(A2:A500)", result: "Live unique list", lesson: "unique" },
  { name: "SORT", category: "Dynamic array", syntax: "=SORT(array;[index];[order];[by_col])", desc: "Returns a sorted copy of a range.", example: "=SORT(A2:D50;3;-1)", result: "Sorted table", lesson: "sort-function" },
  { name: "SORTBY", category: "Dynamic array", syntax: "=SORTBY(array;by_array1;[order1];...)", desc: "Sorts one range using values from another.", example: "=SORTBY(A2:A50;B2:B50;-1)", result: "Names by score", lesson: "sortby" },
  { name: "FILTER", category: "Dynamic array", syntax: "=FILTER(array;include;[if_empty])", desc: "Returns only the rows that meet a condition.", example: '=FILTER(A2:D50;C2:C50="North";"None")', result: "Filtered rows", lesson: "filter-function" },
  { name: "VSTACK", category: "Dynamic array", syntax: "=VSTACK(array1;...)", desc: "Appends ranges one under another.", example: "=VSTACK(Jan!A2:D50;Feb!A2:D50)", result: "Combined table", lesson: "vstack" },
  { name: "HSTACK", category: "Dynamic array", syntax: "=HSTACK(array1;...)", desc: "Places ranges side by side.", example: "=HSTACK(A2:A50;D2:D50)", result: "Two-column report", lesson: "hstack" },
  { name: "CHOOSEROWS", category: "Dynamic array", syntax: "=CHOOSEROWS(array;row1;...)", desc: "Picks named rows from an array.", example: "=CHOOSEROWS(A2:D50;1;3;-1)", result: "Selected rows", lesson: "chooserows" },
  { name: "CHOOSECOLS", category: "Dynamic array", syntax: "=CHOOSECOLS(array;col1;...)", desc: "Picks named columns from an array.", example: "=CHOOSECOLS(A2:Z50;1;4;9)", result: "Slim report", lesson: "choosecols" },
  { name: "TAKE", category: "Dynamic array", syntax: "=TAKE(array;rows;[cols])", desc: "Takes the first or last n rows/columns.", example: "=TAKE(SORT(A2:D50;4;-1);10)", result: "Top 10" },
  { name: "DROP", category: "Dynamic array", syntax: "=DROP(array;rows;[cols])", desc: "Removes the first or last n rows/columns.", example: "=DROP(A1:D50;1)", result: "Data without header" },
  { name: "EXPAND", category: "Dynamic array", syntax: "=EXPAND(array;rows;[cols];[pad])", desc: "Pads an array out to a bigger size.", example: '=EXPAND(A1:B2;4;4;"")', result: "4x4 block" },
  { name: "TOROW", category: "Dynamic array", syntax: "=TOROW(array;[ignore];[by_col])", desc: "Flattens an array into one row.", example: "=TOROW(A2:D10;1)", result: "Single row", lesson: "torow" },
  { name: "TOCOL", category: "Dynamic array", syntax: "=TOCOL(array;[ignore];[by_col])", desc: "Flattens an array into one column.", example: "=TOCOL(A2:D10;1)", result: "Single column", lesson: "tocol" },
  { name: "WRAPROWS", category: "Dynamic array", syntax: "=WRAPROWS(vector;wrap_count;[pad])", desc: "Wraps a list into rows of a fixed width.", example: "=WRAPROWS(A2:A13;3)", result: "4x3 grid" },
  { name: "WRAPCOLS", category: "Dynamic array", syntax: "=WRAPCOLS(vector;wrap_count;[pad])", desc: "Wraps a list into columns of a fixed height.", example: "=WRAPCOLS(A2:A13;4)", result: "4x3 grid" },
  { name: "BYROW", category: "Dynamic array", syntax: "=BYROW(array;LAMBDA(row;calc))", desc: "Applies a calculation to each row.", example: "=BYROW(B2:D50;LAMBDA(r;SUM(r)))", result: "One total per row", lesson: "lambda" },
  { name: "BYCOL", category: "Dynamic array", syntax: "=BYCOL(array;LAMBDA(col;calc))", desc: "Applies a calculation to each column.", example: "=BYCOL(B2:D50;LAMBDA(c;SUM(c)))", result: "Column totals" },
  { name: "MAP", category: "Dynamic array", syntax: "=MAP(array;LAMBDA(v;calc))", desc: "Transforms every value in an array.", example: "=MAP(A2:A50;LAMBDA(v;UPPER(v)))", result: "Transformed list", lesson: "lambda" },
  { name: "REDUCE", category: "Dynamic array", syntax: "=REDUCE(initial;array;LAMBDA(acc;v;calc))", desc: "Accumulates an array down to one value.", example: "=REDUCE(0;A2:A50;LAMBDA(a;v;a+v))", result: "Running total", lesson: "lambda" },
  { name: "SCAN", category: "Dynamic array", syntax: "=SCAN(initial;array;LAMBDA(acc;v;calc))", desc: "Like REDUCE but returns every intermediate value.", example: "=SCAN(0;A2:A50;LAMBDA(a;v;a+v))", result: "Running totals" },

  // ---------- Text ----------
  { name: "LEFT", category: "Text", syntax: "=LEFT(text;[num_chars])", desc: "Characters from the start of a string.", example: '=LEFT("ORD-2024";3)', result: "ORD", lesson: "left-mid-right" },
  { name: "RIGHT", category: "Text", syntax: "=RIGHT(text;[num_chars])", desc: "Characters from the end of a string.", example: '=RIGHT("ORD-2024";4)', result: "2024", lesson: "left-mid-right" },
  { name: "MID", category: "Text", syntax: "=MID(text;start;num_chars)", desc: "Characters from the middle of a string.", example: '=MID("ORD-2024";5;4)', result: "2024", lesson: "left-mid-right" },
  { name: "LEN", category: "Text", syntax: "=LEN(text)", desc: "Number of characters, spaces included.", example: '=LEN("Excel ")', result: "6", lesson: "len" },
  { name: "FIND", category: "Text", syntax: "=FIND(find_text;within_text;[start])", desc: "Position of text inside text, case sensitive.", example: '=FIND("-";A2)', result: "4", lesson: "find" },
  { name: "SEARCH", category: "Text", syntax: "=SEARCH(find_text;within_text;[start])", desc: "Position of text, case insensitive with wildcards.", example: '=SEARCH("a";"Banana")', result: "2", lesson: "search" },
  { name: "SUBSTITUTE", category: "Text", syntax: "=SUBSTITUTE(text;old;new;[instance])", desc: "Replaces text by content.", example: '=SUBSTITUTE(A2;"-";"/")', result: "Swapped text", lesson: "substitute" },
  { name: "REPLACE", category: "Text", syntax: "=REPLACE(old_text;start;num_chars;new_text)", desc: "Replaces text by position.", example: '=REPLACE(A2;1;6;"******")', result: "Masked value", lesson: "substitute" },
  { name: "TRIM", category: "Text", syntax: "=TRIM(text)", desc: "Removes leading, trailing and repeated spaces.", example: '=TRIM("  a  b ")', result: "a b", lesson: "trim" },
  { name: "CLEAN", category: "Text", syntax: "=CLEAN(text)", desc: "Removes non-printing characters.", example: "=CLEAN(A2)", result: "Clean text", lesson: "trim" },
  { name: "UPPER", category: "Text", syntax: "=UPPER(text)", desc: "Converts text to capitals.", example: '=UPPER("excel")', result: "EXCEL", lesson: "lower-upper-proper" },
  { name: "LOWER", category: "Text", syntax: "=LOWER(text)", desc: "Converts text to lower case.", example: '=LOWER("EXCEL")', result: "excel", lesson: "lower-upper-proper" },
  { name: "PROPER", category: "Text", syntax: "=PROPER(text)", desc: "Capitalises the first letter of each word.", example: '=PROPER("john smith")', result: "John Smith", lesson: "lower-upper-proper" },
  { name: "CONCAT", category: "Text", syntax: "=CONCAT(text1;...)", desc: "Joins text, accepts whole ranges.", example: "=CONCAT(A2:D2)", result: "Joined text", lesson: "concat" },
  { name: "CONCATENATE", category: "Text", syntax: "=CONCATENATE(text1;...)", desc: "Legacy join function, replaced by CONCAT.", example: '=CONCATENATE(A2;" ";B2)', result: "Joined text", lesson: "concatenate" },
  { name: "TEXTJOIN", category: "Text", syntax: "=TEXTJOIN(delimiter;ignore_empty;text1;...)", desc: "Joins a range with a separator.", example: '=TEXTJOIN(", ";TRUE;A2:A50)', result: "a, b, c", lesson: "textjoin" },
  { name: "TEXT", category: "Text", syntax: "=TEXT(value;format_text)", desc: "Formats a number as text you control.", example: '=TEXT(A2;"dd mmm yyyy")', result: "04 Mar 2024", lesson: "text-function" },
  { name: "VALUE", category: "Text", syntax: "=VALUE(text)", desc: "Converts text to a number.", example: '=VALUE("1250")', result: "1250", lesson: "value" },
  { name: "NUMBERVALUE", category: "Text", syntax: "=NUMBERVALUE(text;[dec_sep];[group_sep])", desc: "Converts text to a number using chosen separators.", example: '=NUMBERVALUE("1.250,5";",";".")', result: "1250.5" },
  { name: "TEXTBEFORE", category: "Text", syntax: "=TEXTBEFORE(text;delimiter;[instance];...)", desc: "Everything before a delimiter.", example: '=TEXTBEFORE(A2;" ")', result: "First name", lesson: "textbefore-textafter" },
  { name: "TEXTAFTER", category: "Text", syntax: "=TEXTAFTER(text;delimiter;[instance];...)", desc: "Everything after a delimiter.", example: '=TEXTAFTER(A2;"@")', result: "Domain", lesson: "textbefore-textafter" },
  { name: "TEXTSPLIT", category: "Text", syntax: "=TEXTSPLIT(text;col_delim;[row_delim];...)", desc: "Splits text across columns and rows.", example: '=TEXTSPLIT(A2;",")', result: "Split values", lesson: "textsplit" },
  { name: "REPT", category: "Text", syntax: "=REPT(text;number_times)", desc: "Repeats text a number of times.", example: '=REPT("*";5)', result: "*****", note: "Great for in-cell bar charts." },
  { name: "CHAR", category: "Text", syntax: "=CHAR(number)", desc: "The character for a code number.", example: "=CHAR(10)", result: "Line break" },
  { name: "CODE", category: "Text", syntax: "=CODE(text)", desc: "The code number of the first character.", example: '=CODE("A")', result: "65" },
  { name: "UNICHAR", category: "Text", syntax: "=UNICHAR(number)", desc: "The Unicode character for a number.", example: "=UNICHAR(9733)", result: "Star symbol" },
  { name: "EXACT", category: "Text", syntax: "=EXACT(text1;text2)", desc: "Case-sensitive comparison of two strings.", example: '=EXACT("abc";"ABC")', result: "FALSE" },
  { name: "DOLLAR", category: "Text", syntax: "=DOLLAR(number;[decimals])", desc: "Formats a number as currency text.", example: "=DOLLAR(1234.5;2)", result: "$1,234.50" },
  { name: "FIXED", category: "Text", syntax: "=FIXED(number;[decimals];[no_commas])", desc: "Formats a number with fixed decimals as text.", example: "=FIXED(1234.567;1)", result: "1,234.6" },
  { name: "LEFTB", category: "Text", syntax: "=LEFTB(text;num_bytes)", desc: "Byte-based version of LEFT for double-byte languages.", example: "=LEFTB(A2;4)", result: "First bytes" },

  // ---------- Date & Time ----------
  { name: "TODAY", category: "Date", syntax: "=TODAY()", desc: "Today's date, updated automatically.", example: "=TODAY()", result: "Current date", lesson: "date-function" },
  { name: "NOW", category: "Date", syntax: "=NOW()", desc: "Current date and time.", example: "=NOW()", result: "Date + time" },
  { name: "DATE", category: "Date", syntax: "=DATE(year;month;day)", desc: "Builds a date from three numbers.", example: "=DATE(2024;3;4)", result: "04/03/2024", lesson: "date-function" },
  { name: "DAY", category: "Date", syntax: "=DAY(serial_number)", desc: "Day number of a date.", example: "=DAY(TODAY())", result: "1-31", lesson: "day-month-year" },
  { name: "MONTH", category: "Date", syntax: "=MONTH(serial_number)", desc: "Month number of a date.", example: "=MONTH(TODAY())", result: "1-12", lesson: "day-month-year" },
  { name: "YEAR", category: "Date", syntax: "=YEAR(serial_number)", desc: "Year of a date.", example: "=YEAR(TODAY())", result: "2024", lesson: "day-month-year" },
  { name: "HOUR", category: "Date", syntax: "=HOUR(serial_number)", desc: "Hour part of a time.", example: "=HOUR(NOW())", result: "0-23" },
  { name: "MINUTE", category: "Date", syntax: "=MINUTE(serial_number)", desc: "Minute part of a time.", example: "=MINUTE(NOW())", result: "0-59" },
  { name: "SECOND", category: "Date", syntax: "=SECOND(serial_number)", desc: "Second part of a time.", example: "=SECOND(NOW())", result: "0-59" },
  { name: "TIME", category: "Date", syntax: "=TIME(hour;minute;second)", desc: "Builds a time value.", example: "=TIME(9;30;0)", result: "09:30" },
  { name: "WEEKDAY", category: "Date", syntax: "=WEEKDAY(serial;[return_type])", desc: "Day of the week as a number.", example: "=WEEKDAY(A2;2)", result: "1 = Monday", lesson: "weekday" },
  { name: "WEEKNUM", category: "Date", syntax: "=WEEKNUM(serial;[return_type])", desc: "Week number of the year.", example: "=WEEKNUM(A2;2)", result: "1-53" },
  { name: "ISOWEEKNUM", category: "Date", syntax: "=ISOWEEKNUM(date)", desc: "ISO 8601 week number.", example: "=ISOWEEKNUM(A2)", result: "1-53" },
  { name: "EOMONTH", category: "Date", syntax: "=EOMONTH(start_date;months)", desc: "Last day of a month n months away.", example: "=EOMONTH(A2;1)", result: "Month end", lesson: "eomonth" },
  { name: "EDATE", category: "Date", syntax: "=EDATE(start_date;months)", desc: "Same day, n months away.", example: "=EDATE(A2;6)", result: "Six months later", lesson: "eomonth" },
  { name: "DATEDIF", category: "Date", syntax: '=DATEDIF(start;end;"unit")', desc: "Difference between dates in years, months or days.", example: '=DATEDIF(A2;TODAY();"Y")', result: "Age in years", note: 'Units: "Y", "M", "D", "MD", "YM", "YD".' },
  { name: "DAYS", category: "Date", syntax: "=DAYS(end_date;start_date)", desc: "Number of days between two dates.", example: "=DAYS(B2;A2)", result: "Days" },
  { name: "DAYS360", category: "Date", syntax: "=DAYS360(start;end;[method])", desc: "Days between dates on a 360-day year.", example: "=DAYS360(A2;B2)", result: "Accounting days" },
  { name: "NETWORKDAYS", category: "Date", syntax: "=NETWORKDAYS(start;end;[holidays])", desc: "Working days between two dates.", example: "=NETWORKDAYS(A2;B2;Holidays)", result: "Weekdays", lesson: "weekday" },
  { name: "NETWORKDAYS.INTL", category: "Date", syntax: "=NETWORKDAYS.INTL(start;end;[weekend];[holidays])", desc: "Working days with a custom weekend.", example: "=NETWORKDAYS.INTL(A2;B2;7)", result: "Working days" },
  { name: "WORKDAY", category: "Date", syntax: "=WORKDAY(start;days;[holidays])", desc: "The date n working days ahead.", example: "=WORKDAY(A2;10;Holidays)", result: "Delivery date" },
  { name: "WORKDAY.INTL", category: "Date", syntax: "=WORKDAY.INTL(start;days;[weekend];[holidays])", desc: "WORKDAY with a custom weekend.", example: "=WORKDAY.INTL(A2;10;7)", result: "Target date" },
  { name: "YEARFRAC", category: "Date", syntax: "=YEARFRAC(start;end;[basis])", desc: "Fraction of a year between two dates.", example: "=YEARFRAC(A2;B2)", result: "0.5" },
  { name: "DATEVALUE", category: "Date", syntax: "=DATEVALUE(date_text)", desc: "Converts a text date to a real date.", example: '=DATEVALUE("04/03/2024")', result: "45355", lesson: "value" },
  { name: "TIMEVALUE", category: "Date", syntax: "=TIMEVALUE(time_text)", desc: "Converts text to a time value.", example: '=TIMEVALUE("09:30")', result: "0.3958" },

  // ---------- Financial ----------
  { name: "PMT", category: "Financial", syntax: "=PMT(rate;nper;pv;[fv];[type])", desc: "Fixed periodic loan repayment.", example: "=-PMT(5%/12;300;250000)", result: "1535.19", lesson: "pmt" },
  { name: "PPMT", category: "Financial", syntax: "=PPMT(rate;per;nper;pv;[fv];[type])", desc: "Principal part of a chosen payment.", example: "=-PPMT(5%/12;1;300;250000)", result: "Capital repaid", lesson: "ppmt-ipmt" },
  { name: "IPMT", category: "Financial", syntax: "=IPMT(rate;per;nper;pv;[fv];[type])", desc: "Interest part of a chosen payment.", example: "=-IPMT(5%/12;1;300;250000)", result: "Interest paid", lesson: "ppmt-ipmt" },
  { name: "PV", category: "Financial", syntax: "=PV(rate;nper;pmt;[fv];[type])", desc: "Present value of a stream of payments.", example: "=-PV(6%/12;120;1000)", result: "Today's value", lesson: "pv" },
  { name: "FV", category: "Financial", syntax: "=FV(rate;nper;pmt;[pv];[type])", desc: "Future value of a savings plan.", example: "=-FV(6%/12;240;200)", result: "Final balance", lesson: "fv" },
  { name: "NPER", category: "Financial", syntax: "=NPER(rate;pmt;pv;[fv];[type])", desc: "Number of periods needed.", example: "=NPER(5%/12;-1500;250000)", result: "Months to repay" },
  { name: "RATE", category: "Financial", syntax: "=RATE(nper;pmt;pv;[fv];[type];[guess])", desc: "Interest rate per period.", example: "=RATE(60;-350;18000)*12", result: "Annual rate" },
  { name: "NPV", category: "Financial", syntax: "=NPV(rate;value1;...)", desc: "Net present value of uneven cash flows.", example: "=NPV(8%;B2:B11)+B1", result: "Project value", lesson: "pv" },
  { name: "XNPV", category: "Financial", syntax: "=XNPV(rate;values;dates)", desc: "NPV with actual dates.", example: "=XNPV(8%;B2:B11;A2:A11)", result: "Dated NPV" },
  { name: "IRR", category: "Financial", syntax: "=IRR(values;[guess])", desc: "Internal rate of return.", example: "=IRR(B2:B11)", result: "12.4%" },
  { name: "XIRR", category: "Financial", syntax: "=XIRR(values;dates;[guess])", desc: "IRR with actual dates.", example: "=XIRR(B2:B11;A2:A11)", result: "13.1%" },
  { name: "MIRR", category: "Financial", syntax: "=MIRR(values;finance_rate;reinvest_rate)", desc: "Modified internal rate of return.", example: "=MIRR(B2:B11;8%;6%)", result: "10.2%" },
  { name: "SLN", category: "Financial", syntax: "=SLN(cost;salvage;life)", desc: "Straight-line depreciation per period.", example: "=SLN(30000;3000;5)", result: "5400" },
  { name: "DB", category: "Financial", syntax: "=DB(cost;salvage;life;period)", desc: "Declining balance depreciation.", example: "=DB(30000;3000;5;1)", result: "Year 1 charge" },
  { name: "DDB", category: "Financial", syntax: "=DDB(cost;salvage;life;period;[factor])", desc: "Double-declining depreciation.", example: "=DDB(30000;3000;5;1)", result: "Year 1 charge" },
  { name: "SYD", category: "Financial", syntax: "=SYD(cost;salvage;life;per)", desc: "Sum-of-years-digits depreciation.", example: "=SYD(30000;3000;5;1)", result: "Year 1 charge" },
  { name: "EFFECT", category: "Financial", syntax: "=EFFECT(nominal_rate;npery)", desc: "Effective annual rate.", example: "=EFFECT(6%;12)", result: "6.17%" },
  { name: "NOMINAL", category: "Financial", syntax: "=NOMINAL(effect_rate;npery)", desc: "Nominal annual rate.", example: "=NOMINAL(6.17%;12)", result: "6.00%" },
  { name: "CUMIPMT", category: "Financial", syntax: "=CUMIPMT(rate;nper;pv;start;end;type)", desc: "Cumulative interest between two periods.", example: "=CUMIPMT(5%/12;300;250000;1;12;0)", result: "Year 1 interest" },
  { name: "CUMPRINC", category: "Financial", syntax: "=CUMPRINC(rate;nper;pv;start;end;type)", desc: "Cumulative principal between two periods.", example: "=CUMPRINC(5%/12;300;250000;1;12;0)", result: "Year 1 capital" },

  // ---------- Information ----------
  { name: "ISBLANK", category: "Information", syntax: "=ISBLANK(value)", desc: "TRUE when a cell is truly empty.", example: "=ISBLANK(A2)", result: "TRUE / FALSE", lesson: "isblank" },
  { name: "ISNUMBER", category: "Information", syntax: "=ISNUMBER(value)", desc: "TRUE when the value is a number.", example: "=ISNUMBER(A2)", result: "TRUE / FALSE" },
  { name: "ISTEXT", category: "Information", syntax: "=ISTEXT(value)", desc: "TRUE when the value is text.", example: "=ISTEXT(A2)", result: "TRUE / FALSE" },
  { name: "ISERROR", category: "Information", syntax: "=ISERROR(value)", desc: "TRUE for any error value.", example: "=ISERROR(B2/C2)", result: "TRUE / FALSE" },
  { name: "ISNA", category: "Information", syntax: "=ISNA(value)", desc: "TRUE only for the #N/A error.", example: "=ISNA(VLOOKUP(...))", result: "TRUE / FALSE" },
  { name: "ISEVEN", category: "Information", syntax: "=ISEVEN(number)", desc: "TRUE when the number is even.", example: "=ISEVEN(4)", result: "TRUE" },
  { name: "ISODD", category: "Information", syntax: "=ISODD(number)", desc: "TRUE when the number is odd.", example: "=ISODD(4)", result: "FALSE" },
  { name: "ISFORMULA", category: "Information", syntax: "=ISFORMULA(reference)", desc: "TRUE when the cell contains a formula.", example: "=ISFORMULA(B2)", result: "TRUE / FALSE" },
  { name: "ISLOGICAL", category: "Information", syntax: "=ISLOGICAL(value)", desc: "TRUE when the value is TRUE or FALSE.", example: "=ISLOGICAL(A2)", result: "TRUE / FALSE" },
  { name: "NA", category: "Information", syntax: "=NA()", desc: "Returns #N/A on purpose, useful to break chart lines.", example: "=NA()", result: "#N/A" },
  { name: "TYPE", category: "Information", syntax: "=TYPE(value)", desc: "Number describing the data type.", example: "=TYPE(A2)", result: "1 = number" },
  { name: "CELL", category: "Information", syntax: "=CELL(info_type;[reference])", desc: "Information about a cell's format or position.", example: '=CELL("address";A2)', result: "$A$2" },
  { name: "INFO", category: "Information", syntax: "=INFO(type_text)", desc: "Information about the environment.", example: '=INFO("release")', result: "Excel version" },
  { name: "SHEET", category: "Information", syntax: "=SHEET([value])", desc: "Sheet number of a reference.", example: "=SHEET()", result: "2" },
  { name: "SHEETS", category: "Information", syntax: "=SHEETS([reference])", desc: "Number of sheets in a reference.", example: "=SHEETS()", result: "5" },
  { name: "ERROR.TYPE", category: "Information", syntax: "=ERROR.TYPE(error_val)", desc: "Number identifying which error occurred.", example: "=ERROR.TYPE(#N/A)", result: "7" },

  // ---------- Database ----------
  { name: "DSUM", category: "Database", syntax: "=DSUM(database;field;criteria)", desc: "Sums a column using a criteria range.", example: '=DSUM(A1:E50;"Amount";H1:I2)', result: "Filtered total" },
  { name: "DCOUNT", category: "Database", syntax: "=DCOUNT(database;field;criteria)", desc: "Counts numeric cells matching the criteria range.", example: '=DCOUNT(A1:E50;"Amount";H1:I2)', result: "Count" },
  { name: "DAVERAGE", category: "Database", syntax: "=DAVERAGE(database;field;criteria)", desc: "Averages a column using a criteria range.", example: '=DAVERAGE(A1:E50;"Amount";H1:I2)', result: "Mean" },
  { name: "DMAX", category: "Database", syntax: "=DMAX(database;field;criteria)", desc: "Largest matching value.", example: '=DMAX(A1:E50;"Amount";H1:I2)', result: "Max" },
  { name: "DMIN", category: "Database", syntax: "=DMIN(database;field;criteria)", desc: "Smallest matching value.", example: '=DMIN(A1:E50;"Amount";H1:I2)', result: "Min" },
  { name: "DGET", category: "Database", syntax: "=DGET(database;field;criteria)", desc: "Returns the single record that matches.", example: '=DGET(A1:E50;"Customer";H1:I2)', result: "One value" },
];

export const FN_CATEGORIES = Array.from(
  new Set(FUNCTIONS.map((f) => f.category)),
).sort();

export const fnBySlug = (slug: string) =>
  FUNCTIONS.find((f) => f.name.toLowerCase().replace(/\./g, "-") === slug);

export const fnSlug = (name: string) =>
  name.toLowerCase().replace(/\./g, "-");
