export type Lesson={slug:string;title:string;track:string;level:"Beginner"|"Intermediate"|"Advanced";summary:string;objectives:string[];syntax?:string;steps:Array<{title:string;detail?:string;formula?:string}>;shortcuts?:Array<[string,string]>;formulas?:Array<{label:string;code:string}>;example?:{caption?:string;headers:string[];rows:string[][]};tips?:string[];mistakes?:string[];practice?:{task:string;answer:string};quiz:Array<{q:string;options:string[];answer:number;explain:string}>};
export const TRACKS=[
{id:"foundations",icon:"🧭",name:"Excel Foundations",blurb:"Workbook structure, navigation and reliable spreadsheet habits."},
{id:"cleaning",icon:"🧹",name:"Data Cleaning",blurb:"Turn inconsistent spreadsheet data into analysis-ready tables."},
{id:"lookups",icon:"🔎",name:"Lookups & References",blurb:"Connect tables and retrieve values reliably."},
{id:"logic",icon:"🧠",name:"Logic & Criteria",blurb:"Build conditional calculations and exception checks."},
{id:"analysis",icon:"📊",name:"Analysis",blurb:"Summarise, filter and explore business data."},
{id:"finance",icon:"💰",name:"Financial Modelling",blurb:"Apply practical financial functions and modelling patterns."},
{id:"productivity",icon:"⚡",name:"Productivity",blurb:"Use shortcuts and reusable formula patterns."},
{id:"advanced",icon:"🚀",name:"Advanced Excel",blurb:"Use dynamic arrays and robust modern formulas."}
] as const;
const quiz={q:"Which symbol begins an Excel formula?",options:["=","#","@","$"],answer:0,explain:"Excel formulas begin with an equals sign."};
const lesson=(slug:string,title:string,track:string,level:Lesson["level"],summary:string,syntax:string,steps:Lesson["steps"],objectives:string[]):Lesson=>({slug,title,track,level,summary,syntax,steps,objectives,quiz:[quiz]});
export const LESSONS:Lesson[]=[
lesson("getting-started","Excel Fundamentals — Getting Started","foundations","Beginner","Understand worksheets, cells, rows, columns and formulas.","=A1+B1",[{title:"Identify the grid",detail:"Columns use letters and rows use numbers; their intersection is a cell."},{title:"Enter a formula",detail:"Select a cell, type =, then reference cells or values."},{title:"Review the result",detail:"Press Enter and check the formula bar."}],["Navigate a worksheet","Recognise cell references","Create a basic formula"]),
lesson("clean-data","Clean Spreadsheet Data — TRIM and CLEAN","cleaning","Beginner","Remove unwanted spaces and non-printing characters before analysis.","=TRIM(CLEAN(A2))",[{title:"Create a clean column",detail:"Add a new column beside the source data."},{title:"Remove non-printing characters",formula:"=CLEAN(A2)"},{title:"Collapse repeated spaces",formula:"=TRIM(CLEAN(A2))"}],["Clean text consistently","Prepare data for matching","Reduce hidden formatting problems"]),
lesson("xlookup","XLOOKUP — Modern Table Lookup","lookups","Intermediate","Find a key in one range and return the corresponding value from another.","=XLOOKUP(A2,IDRange,NameRange,\"Not found\")",[{title:"Choose a stable key",detail:"Use an account, customer or product ID."},{title:"Select lookup and return ranges",detail:"The ranges must align by row."},{title:"Add a fallback",formula:"=XLOOKUP(A2,IDRange,NameRange,\"Not found\")"}],["Build a modern lookup","Handle missing matches","Return values from either side of a key"]),
lesson("sumifs","SUMIFS — Multi-Criteria Totals","logic","Intermediate","Sum values only when multiple conditions are satisfied.","=SUMIFS(Sales,Region,A2,Month,B2)",[{title:"Choose the sum range",detail:"Use the numeric measure."},{title:"Add criteria pairs",detail:"Specify each criteria range and its required value."},{title:"Audit the result",detail:"Confirm all ranges have matching dimensions."}],["Build multi-condition totals","Audit criteria ranges","Create reusable reports"]),
lesson("filter","FILTER — Dynamic Data Extraction","analysis","Intermediate","Return only rows that meet a condition and let the result spill automatically.","=FILTER(A2:D100,D2:D100=\"Open\",\"No matches\")",[{title:"Select the source array",detail:"Include the complete table."},{title:"Create the include test",formula:"D2:D100=\"Open\""},{title:"Handle empty results",formula:"=FILTER(A2:D100,D2:D100=\"Open\",\"No matches\")"}],["Extract filtered tables","Use dynamic arrays","Handle no-result cases"]),
lesson("if","IF — Conditional Logic","logic","Beginner","Return different results based on a condition.","=IF(B2>=70,\"Pass\",\"Review\")",[{title:"Write the condition",formula:"B2>=70"},{title:"Set the true result",detail:"Return Pass when the condition is met."},{title:"Set the false result",detail:"Return Review otherwise."}],["Create conditional outputs","Build exception flags","Read nested logic"]),
lesson("sumproduct","SUMPRODUCT — Weighted Analysis","analysis","Advanced","Multiply corresponding values and aggregate the results.","=SUMPRODUCT(B2:B20,C2:C20)",[{title:"Align the ranges",detail:"Use equal-sized ranges."},{title:"Multiply row by row",detail:"Each position is multiplied with its counterpart."},{title:"Aggregate products",formula:"=SUMPRODUCT(B2:B20,C2:C20)"}],["Calculate weighted totals","Model quantity times price","Understand array calculations"]),
lesson("xirr","XIRR — Irregular Cash Flows","finance","Advanced","Calculate an annualised return for cash flows on irregular dates.","=XIRR(B2:B8,A2:A8)",[{title:"List cash flows",detail:"Use negative investments and positive proceeds."},{title:"Provide matching dates",detail:"Every cash flow needs a corresponding date."},{title:"Calculate the return",formula:"=XIRR(CashFlows,Dates)"}],["Model irregular cash flows","Keep dates aligned","Interpret annualised return"]),
{slug:"cheat-sheet",title:"Excel Cheat Sheet — Shortcuts & Formula Patterns",track:"productivity",level:"Beginner",summary:"A compact reference for frequently used Excel shortcuts and formulas.",objectives:["Navigate faster","Reuse reliable formulas","Diagnose common errors"],shortcuts:[["Ctrl+C","Copy"],["Ctrl+V","Paste"],["Ctrl+Z","Undo"],["Ctrl+F","Find"],["Ctrl+Shift+L","Toggle filters"],["F2","Edit active cell"]],formulas:[{label:"Safe division",code:"=IFERROR(B2/C2,\"-\")"},{label:"Conditional total",code:"=SUMIFS(Amount,Region,A2)"},{label:"Modern lookup",code:"=XLOOKUP(A2,IDs,Names,\"Not found\")"},{label:"Dynamic filter",code:"=FILTER(A2:D100,D2:D100=\"Open\",\"No matches\")"}],steps:[],quiz:[{q:"Which shortcut opens Find?",options:["Ctrl+F","Ctrl+P","Ctrl+N","Ctrl+K"],answer:0,explain:"Ctrl+F opens Find in Excel."}]}
];
export function byTrack(id:string){return LESSONS.filter(l=>l.track===id)}
export function bySlug(slug:string){return LESSONS.find(l=>l.slug===slug)}
export function neighbours(slug:string){const i=LESSONS.findIndex(l=>l.slug===slug);return{index:i,prev:i>0?LESSONS[i-1]:undefined,next:i>=0&&i<LESSONS.length-1?LESSONS[i+1]:undefined}}
